insert into tb_parametro (descricao, sigla, valor) values ('Indica qual IP a aplicação será executada em Teste', 'IP_TESTE', '192.168.1.5');
insert into tb_parametro (descricao, sigla, valor) values ('Indica qual IP a aplicação será executada em Homologação', 'IP_HOMOLOGACAO', '192.168.1.5');
insert into tb_parametro (descricao, sigla, valor) values ('Indica qual IP a aplicação será executada em Produção', 'IP_PRODUCAO', '192.168.1.5');
